### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by lalal321** [EmaroLab/mocap2mav#12]
Hello, I am reading your paper "Marea project: UAV Landing procedure on a moving and floating platform" just now, and find your algorithm link here, it is not a standard ROS package,  how would I to use it? Do you have any instructions? And which folder directory is your algorithm locating ? Thank you.

**Comment by andrea-nisti** [comment]
Hello,

sorry for the delayed answer but the package is not maintained right now. In order to use it with ros you need a bridge from LCM to ROS topics (https://github.com/andrea-nisti/lcm_bridge).

In order to run the package check the scripts in the root directory, moreover you need to initialize and sync git module after compilation. There should be a script that does everything for you. The core is in the lib folder, there you can find the automatic and executioner module
